spring:
  datasource:
    username: "${db.username}"
    password: "${db.password}"
    url: "jdbc:postgresql://localhost:5432/certiCampus"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
