db:
  maximum-pool-size: 5
  connection-timeout: 20000
  url: jdbc:postgresql://localhost:5432/certiCampus
  driverClassName: org.postgresql.Driver

spring:
  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${db.url}
    driver-class-name: ${db.driverClassName}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
